# MySQL Configuration
spring.datasource.url: jdbc:mysql://localhost:3306/yourdb
spring.datasource.username: root
spring.datasource.password: yourpassword
spring.jpa.hibernate.ddl-auto: update

# JMS Configuration
spring.jms.listener.auto-startup: true
#spring.jms.pub-sub-domain: false

# Retry Configuration
retry.max.attempts: 5
retry.backoff: 2000

#hawtio.authenticationEnabled: true
#hawtio.url-mapping: /hawtio/*
  
spring.activemq.broker-url: tcp://localhost:61616
spring.activemq.user: admin
spring.activemq.password: admin
spring.activemq.packages.trust-all: true
spring.jms.pub-sub-domain: false

jms:
  queues:
    inbound:
      upstream: AMPS.To.FAB

mq:
  connections:
    activemq:
      - connection: ampsConenction
        url:  tcp://localhost:61616
activemq:
  brokerService:
    url:  tcp://localhost:61616
  hawtio:
    authenticationEnabled: false

management:
  endpoint:
    hawtio:
      enable: true
    jolokia:
      enable: true


messagequeue:
    inbound:
      upstream: AMPS.To.FAB
